config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
scope module: :public do
  root to: "homes#top"
  get "/about" => "homes#about", as: 'about'
  resources :items, only: [:index,:show]
  resource :customers, only: [:show,:cofirm]
  get 'customer/edit' => 'customers#edit'
  put 'customer/update' => 'customers#update'
  patch 'customer/update' => 'customers#update'


  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'


  resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create] do
    collection do
      delete 'destroy_all'
    end
  end
  post 'orders/confirm'=>'orders#confirm', as: 'confirm_order'
  get 'orders/complete'=>'orders#complete',as: 'complete_order'
  resources :orders, only: [:new,:create,:index,:show]
  resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  resources :genres, only:[:show]
  get "search" => "searches#search"
end

namespace :admin do
  get "/" => "orders#index"
  resources :items, only: [:index,:new,:create,:show,:edit,:update]
  resources :genres, only: [:index,:create,:edit,:update,:destroy]
  resources :customers, only: [:index,:show,:edit,:update]do
    resources :order_detailes, only: [:index]
  end
  resources :orders, only: [:show,:update,:index]
  resources :order_detailes, only: [:update]
  get "search" => "searches#search"
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  enum user_status: { false: 0, true: 1 }

  with_options presence: true, format: { with:/\A[ぁ-んァ-ン一-龥]/, message: '日本語で入力してください' } do
    validates :first_name
    validates :last_name
  end

  with_options presence: true, format: { with:/\A[ァ-ヶー－]+\z/, message: '全角カタカナで入力してください' } do
    validates :first_name_kana
    validates :last_name_kana
  end

  validates :phonenumber, uniqueness: true, format: { with: /\A\d{10,11}\z/ }
  validates :postcode, format: {with: /\A\d{7}\z/}, numericality: { only_integer: true }

  validates :address, presence: true

  def self.looks(search, word)
    where("last_name LIKE? OR first_name LIKE? OR last_name_kana LIKE? OR first_name_kana LIKE?", "%#{word}%", "%#{word}%", "%#{word}%", "%#{word}%")
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end


  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :user_status)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container py-4">
  <div class="row mb-3">
　　<h4>会員情報編集(<%= @customer.first_name %><%= @customer.last_name %>さん)</h4>
　</div>

  <div class="col">
    <% if @customer.errors.any? %>
      <div class="alert alert-warning">
        <ul>
          <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <%= form_with model:@customer, url: admin_customer_path, method: :PATCH, local:true do |f| %>
  <div class="form-group row">
    <div class="col-md-3">会員ID</div>
    <div class="col-md-2"><%= @customer.id %></div>
  </div>
  <div class="form-group row">
    <%= f.label :氏名, class: "col-md-3" %>
    <%= f.text_field :last_name, class: "col-md-2 form-control" %>
    <%= f.text_field :first_name, class: "col-md-2 form-control ml-3" %>
  </div>
  <div class="form-group row">
    <%= f.label :フリガナ, class: "col-md-3" %>
    <%= f.text_field :last_name_kana, class: "col-md-2 form-control" %>
    <%= f.text_field :first_name_kana, class: "col-md-2 form-control ml-3" %>
  </div>
  <div class="form-group row">
    <%= f.label :郵便番号, class: "col-md-3" %>
    <%= f.text_field :postcode, class: "col-md-5 form-control" %>
  </div>
  <div class="form-group row">
    <%= f.label :住所, class: "col-md-3" %>
    <%= f.text_field :address, class: "col-md-5 form-control" %>
  </div>
  <div class="form-group row">
    <%= f.label :電話番号, class: "col-md-3" %>
    <%= f.text_field :phonenumber, class: "col-md-5 form-control" %>
  </div>
  <div class="form-group row">
    <%= f.label :メールアドレス, class: "col-md-3" %>
    <%= f.email_field :email, class: "col-md-5 form-control" %>
  </div>
  <div class="form-group row">
    <%= f.label :会員ステータス, class: "col-md-3" %>
    <label><%= f.radio_button :user_status?, "true", checked: "false" %>有効</label>
    <label class="ml-3"><%= f.radio_button :user_status, "false" %>退会</label>
  </div>

  <div class="form-group row">
    <%= f.submit "変更を保存", class: "btn btn-success col-md-2 offset-3" %>
  </div>
<% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container px-5 py-4">
  <div class="row align-items-center justify-content-between">
    <h4 class="col-3">会員一覧</h4>
  </div>

  <table class="table table-hover table-inverse cart_products">
    <tr>
      <th class="table-secondary">会員ID</th>
      <th class="table-secondary">氏名</th>
      <th class="table-secondary">メールアドレス</th>
      <th class="table-secondary">ステータス</th>
    </tr>
    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.id %></td>
      <td>
        <%= link_to admin_customer_path(customer) do %>
          <%= customer.last_name %><%= customer.first_name %>
        <% end %>
      </td>
      <td><%= customer.email %></td>

      <% if customer.user_status == "true" %>
        <td>有効</td>
      <% else customer.user_status == "false" %>
        <td>退会</td>
      <% end %>
    </tr>
    <% end %>
  </table>

</div>

app/views/admin/customers/show.html.erb
<div class="container py-4">
  <div class="row">
    <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class="table cart_items">
        <tr>
          <th style="width:30%">会員ID</th>
          <td style="width:70%"><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %> <%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.phonenumber %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <% if @customer.user_status == "true" %>
            <td>有効</td>
          <% else @customer.user_status == "false" %>
            <td>退会</td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5 clearfix">

      <div class="float-right"><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></div>
    </div>
    <div class="col-md-7">
      <%= link_to "注文履歴一覧を見る", admin_customer_order_detailes_path(@customer), class: "btn btn-primary" %>
    </div>
  </div>

</div>