config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
scope module: :public do
  root to: "homes#top"
  get "/about" => "homes#about", as: 'about'
  resources :items, only: [:index,:show]
  resource :customers, only: [:show,:cofirm]
  get 'customer/edit' => 'customers#edit'
  put 'customer/update' => 'customers#update'
  patch 'customer/update' => 'customers#update'


  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'


  resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create] do
    collection do
      delete 'destroy_all'
    end
  end
  post 'orders/confirm'=>'orders#confirm', as: 'confirm_order'
  get 'orders/complete'=>'orders#complete',as: 'complete_order'
  resources :orders, only: [:new,:create,:index,:show]
  resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  resources :genres, only:[:show]
  get "search" => "searches#search"
end

namespace :admin do
  get "/" => "orders#index"
  resources :items, only: [:index,:new,:create,:show,:edit,:update]
  resources :genres, only: [:index,:create,:edit,:update,:destroy]
  resources :customers, only: [:index,:show,:edit,:update]do
    resources :order_detailes, only: [:index]
  end
  resources :orders, only: [:show,:update,:index]
  resources :order_detailes, only: [:update]
  get "search" => "searches#search"
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details,dependent: :destroy
  belongs_to :customer

  validates :postcode, presence: true
  validates :address, presence: true
  validates :address_name, presence: true
  validates :payment, presence: true
  
  
  enum payment:{ credit_card:0 ,transfer: 1}
  enum order_status:{ waiting_for_payment:0,payment_confirmation:1,under_construction:2,shipping_preparation:3,sent:4}



  def add_tax
    (item.price * 1.08).round
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @orders = Order.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "payment_confirmation"
       @order.order_details.update_all(product_status: 1)
    end
    
    redirect_to request.referer
  end


  private

  def order_params
    params.require(:order).permit(:order_status)
  end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container px-5 py-4">
  <div class="row align-items-center">
    <div class="col-3">
      <h4>注文履歴一覧</h4></div>
    </div>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th class="table-secondary">購入日時</th>
          <th class="table-secondary">購入者</th>
          <th class="table-secondary">注文個数</th>
          <th class="table-secondary">注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td>
           <%= link_to admin_order_path(order.id), class: 'btn btn-default' do %>
             <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
           <% end %>
          </td>
          <td> <%= order.customer.last_name %><%= order.customer.first_name %></td>
          <td><%= order.order_details.sum(:order_quantity) %></td>
          <td><%= order.order_status_i18n %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-ml-9 mt-sm-3 " >
      <h4>注文履歴詳細</h4>
        <table>
        <tr>
          <th>購入者</th>
          <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
         </tr>
        <tr>
          <th>注文日</th>
          <td> <%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.postcode %>　<%= @order.address %></td>
        </tr>
        <tr>
          <th></th>
          <td><%= @order.address_name %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス　</th>
         <td>
            <%= form_with model: @order, url: admin_order_path(@order.id),class: "form-row" ,method: :patch do |f| %>
            <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
            <%= f.submit "更新", class:"btn btn-outline-info btn-sm" %>
            <% end %>
          </td>
        </tr>
      </table>
      <table class='table table-hover table-inverse mt-sm-4'>
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.item_name %></td>
              <td><%= order_detail.item.add_tax_price %> 円</td>
              <td><%= order_detail.order_quantity %> 個</td>
              <td><%= (order_detail.item.add_tax_price * order_detail.order_quantity).to_s(:delimited) %> 円</td>
              <td>
                <%= form_with model: order_detail, url: admin_order_detaile_path(order_detail), method: :patch do |f| %>
                  <%= f.select :product_status, OrderDetail.product_statuses.keys.map {|u| [I18n.t("enums.order_detail.product_status.#{u}"), u]} %>
                  <%= f.submit "更新", class:"btn btn-outline-info btn-sm" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="absolute_test1">
    <h4>商品合計<%= (@order.billing_amount-@order.postage).to_s(:delimited) %> 円</h4>
    <h4>送料　　　   <%= @order.postage %>円</h4>
    <h4>請求金額 <%= @order.billing_amount.to_s(:delimited) %>円</h4>
</div>