config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
scope module: :public do
  root to: "homes#top"
  get "/about" => "homes#about", as: 'about'
  resources :items, only: [:index,:show]
  resource :customers, only: [:show,:cofirm]
  get 'customer/edit' => 'customers#edit'
  put 'customer/update' => 'customers#update'
  patch 'customer/update' => 'customers#update'


  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'


  resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create] do
    collection do
      delete 'destroy_all'
    end
  end
  post 'orders/confirm'=>'orders#confirm', as: 'confirm_order'
  get 'orders/complete'=>'orders#complete',as: 'complete_order'
  resources :orders, only: [:new,:create,:index,:show]
  resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  resources :genres, only:[:show]
  get "search" => "searches#search"
end

namespace :admin do
  get "/" => "orders#index"
  resources :items, only: [:index,:new,:create,:show,:edit,:update]
  resources :genres, only: [:index,:create,:edit,:update,:destroy]
  resources :customers, only: [:index,:show,:edit,:update]do
    resources :order_detailes, only: [:index]
  end
  resources :orders, only: [:show,:update,:index]
  resources :order_detailes, only: [:update]
  get "search" => "searches#search"
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    @range = params[:range]
    if @range == "商品"
      @items = Item.looks(params[:search], params[:word])
    else
      @customers = Customer.looks(params[:search], params[:word])
    end
    @word = params[:word]
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/_search_form.html.erb
<div class="search_form">
  <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word %>
    <%= f.select :range, options_for_select([['商品'], ['会員']]) %>
    <%= f.submit "検索", class: "btn btn-outline-info" %>
  <% end %>
</div>

app/views/admin/searches/search.html.erb
<% if @range == "商品" %>

  <div class="container px-5 py-4">
    <div class="row align-items-center justify-content-between mt-3">

      <p class="col-5">
        <span class="h4">『<%= @word %>』の商品一覧</span>(全<%= @items.count %>件)
      </p>
        <div class="col-1">
          <%= link_to new_admin_item_path do %>
          <i class="fas fa-plus-circle fa-3x text-secondary" title="新規登録"></i>
          <% end %>
        </div>
      </div>

      <table class='table table-hover table-inverse mt-2'>
        <thead>
          <tr>
            <th class="table-secondary">商品ID</th>
            <th class="table-secondary">商品名</th>
            <th class="table-secondary">税抜価格</th>
            <th class="table-secondary">ジャンル</th>
            <th class="table-secondary">ステータス</th>
          </tr>
        </thead>

        <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id) do %>
              <%= item.item_name %>
              <% end %>
            </td>
            <td><%= item.price.to_s(:delimited) %>円</td>
            <td><%= item.genre.genre_name %></td>
            <td>
              <% if item.item_status == "available" %>
                <p class="text-success"><%= item.item_status_i18n %></p>
              <% else %>
                <p class="text-black-50"><%= item.item_status_i18n %></p>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

<% else %>
  <div class="container px-5 py-4">
    <div class="row align-items-center justify-content-between mt-3">
      <p class="col-5">
        <span class="h3">『<%= @word %>』の会員一覧</span>(全<%= @customers.count %>件)
      </p>
    </div>

    <table class="table table-hover table-inverse cart_products mt-2">
      <tr>
        <th class="table-secondary">会員ID</th>
        <th class="table-secondary">氏名</th>
        <th class="table-secondary">メールアドレス</th>
        <th class="table-secondary">ステータス</th>
      </tr>

    <% @customers.each do |customer| %>

      <tr>
        <td><%= customer.id %></td>
        <td>
          <%= link_to admin_customer_path(customer) do %>
            <%= customer.last_name %><%= customer.first_name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>

        <% if customer.user_status == "true" %>
          <td>有効</td>
        <% else customer.user_status == "false" %>
          <td>退会</td>
        <% end %>
      </tr>
    <% end %>
    </table>

  </div>

<% end %>