config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
scope module: :public do
  root to: "homes#top"
  get "/about" => "homes#about", as: 'about'
  resources :items, only: [:index,:show]
  resource :customers, only: [:show,:cofirm]
  get 'customer/edit' => 'customers#edit'
  put 'customer/update' => 'customers#update'
  patch 'customer/update' => 'customers#update'


  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'


  resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create] do
    collection do
      delete 'destroy_all'
    end
  end
  post 'orders/confirm'=>'orders#confirm', as: 'confirm_order'
  get 'orders/complete'=>'orders#complete',as: 'complete_order'
  resources :orders, only: [:new,:create,:index,:show]
  resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  resources :genres, only:[:show]
  get "search" => "searches#search"
end

namespace :admin do
  get "/" => "orders#index"
  resources :items, only: [:index,:new,:create,:show,:edit,:update]
  resources :genres, only: [:index,:create,:edit,:update,:destroy]
  resources :customers, only: [:index,:show,:edit,:update]do
    resources :order_detailes, only: [:index]
  end
  resources :orders, only: [:show,:update,:index]
  resources :order_detailes, only: [:update]
  get "search" => "searches#search"
end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand" href="/"><%= image_tag"naganocake.jpg",size:"150x70" %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if  admin_signed_in? %>
          <li>
            <%= link_to admin_items_path, class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
              会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_path, class: 'nav-link text-light' do %>
              注文履歴一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_genres_path, class: 'nav-link text-light' do %>
              ジャンル一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              ログアウト
            <% end %>
          </li>
          <li>
            <%= render 'admin/searches/search_form' %>
          </li>
        <% elsif customer_signed_in? %>
          <li>
            <%= link_to customers_path, class: 'nav-link text-light' do %>
              マイページ
            <% end %>
          </li>
          <li>
            <%= link_to items_path, class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to cart_items_path, class: 'nav-link text-light' do %>
              カート
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
              ログアウト
            <% end %>
          </li>
          <li>
            <%= render 'public/searches/search_form' %>
          </li>
        <% else %>
          <li>
            <%= link_to about_path, class: 'nav-link text-light' do %>
              About
            <% end %>
          </li>
          <li>
            <%= link_to items_path, class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
              新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
               ログイン
            <% end %>
          </li>
          <li>
            <%= render 'public/searches/search_form' %>
          </li>
        <% end %>
        </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  </head>
    <%= render 'layouts/header' %>
  <body>
    <p id="notice"><%= notice %></p>
    
    <%= yield %>
  </body>

  <footer class="fixed-bottom text-center text-white" style="background-color: #f2ebd1;">
  <div class="container">
    <section class="mb-2">
      <a class="text-dark">© ながのCAKE</a>
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="https://www.instagram.com/"
        role="button"
        data-mdb-ripple-color="dark">
        <i class="fab fa-instagram"></i> instagram
      </a>
    </section>
  </div>
</footer>
</html>